version: '3'
services:
  authapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authapp
    network_mode: host
    ports:
     - 8080:8080
    volumes:
     - ./logs:/bas/logs
     - ./flask_session:/bas/flask_session
     - ./app.db:/bas/app.db
     - /etc/localtime:/etc/localtime:ro
    environment:
     - CONFIG_ENV=config_dev.py
     - BAS_DB_USER=root
     - BAS_DB_NAME=app
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
